Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
