default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV['POSTGRES_HOST'] %>
  port:     <%= ENV['POSTGRES_PORT'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wheatherapp_development

test:
  <<: *default
  database: wheatherapp_test

citest:
  adapter: postgresql
  username: runner
  pool: 5
  timeout: 5000
  port: 5432
  host: postgres
  database: wheatherapp_test

production:
  <<: *default
  database: wheatherapp_production
